# Generated by Django 5.2.17 on 2026-09-02 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('items_description', models.TextField()),
                ('occupancy_level_reported', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('trash_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='collection_points.trashbin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisposalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disposals/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='disposals.disposal')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(default='Registro de descarte', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='points_transaction', to='disposals.disposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisposalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disposals.disposal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disposals.wastecategory')),
            ],
        ),
        migrations.AddField(
            model_name='disposal',
            name='categories',
            field=models.ManyToManyField(through='disposals.DisposalCategory', to='disposals.wastecategory'),
        ),
        migrations.AddConstraint(
            model_name='disposalcategory',
            constraint=models.UniqueConstraint(fields=('disposal', 'category'), name='unique_disposal_category'),
        ),
    ]
